insert into wands (wood, length, core) values ('oak', 11, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (17, 'ravenclaw', 'owl', (select count(id) from wands));
 insert into wands (wood, length, core) values ('oak', 13, 'kneazle whisper');
insert into hp_students (age, house, pet, wand_id) values (13, 'gryffindor', 'toad', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 10, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (12, 'ravenclaw', 'owl', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 11, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (12, 'ravenclaw', 'owl', (select count(id) from wands));
 insert into wands (wood, length, core) values ('willow', 12, 'unicorn hair');
insert into hp_students (age, house, pet, wand_id) values (13, 'ravenclaw', 'rat', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 10, 'phoenix feather');
insert into hp_students (age, house, pet, wand_id) values (10, 'slytherin', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('willow', 11, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (12, 'ravenclaw', 'owl', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 11, 'kneazle whisper');
insert into hp_students (age, house, pet, wand_id) values (12, 'slytherin', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 11, 'phoenix feather');
insert into hp_students (age, house, pet, wand_id) values (10, 'slytherin', 'hippogriff', (select count(id) from wands));
 insert into wands (wood, length, core) values ('willow', 14, 'unicorn hair');
insert into hp_students (age, house, pet, wand_id) values (16, 'hufflepuff', 'ferret', (select count(id) from wands));

insert into wands (wood, length, core) values ('holly', 12, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (15, 'hufflepuff', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('oak', 11, 'dragon heartstring');
insert into hp_students (age, house, pet, wand_id) values (11, 'hufflepuff', 'toad', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 13, 'kneazle whisper');
insert into hp_students (age, house, pet, wand_id) values (10, 'ravenclaw', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('oak', 10, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (15, 'ravenclaw', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 12, 'dragon heartstring');
insert into hp_students (age, house, pet, wand_id) values (14, 'hufflepuff', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 10, 'unicorn hair');
insert into hp_students (age, house, pet, wand_id) values (15, 'ravenclaw', 'toad', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 14, 'dragon heartstring');
insert into hp_students (age, house, pet, wand_id) values (13, 'ravenclaw', 'toad', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 13, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (12, 'gryffindor', 'dog', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 15, 'kneazle whisper');
insert into hp_students (age, house, pet, wand_id) values (13, 'hufflepuff', 'dog', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 15, 'phoenix feather');
insert into hp_students (age, house, pet, wand_id) values (14, 'hufflepuff', 'dog', (select count(id) from wands));

insert into wands (wood, length, core) values ('yew', 14, 'dragon heartstring');
insert into hp_students (age, house, pet, wand_id) values (18, 'ravenclaw', 'dog', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 13, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (11, 'hufflepuff', 'owl', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 12, 'kneazle whisper');
insert into hp_students (age, house, pet, wand_id) values (18, 'gryffindor', 'cat', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 11, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (11, 'hufflepuff', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 14, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (12, 'gryffindor', 'owl', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 11, 'veela hair');
insert into hp_students (age, house, pet, wand_id) values (12, 'hufflepuff', 'rat', (select count(id) from wands));
 insert into wands (wood, length, core) values ('oak', 13, 'kneazle whisper');
insert into hp_students (age, house, pet, wand_id) values (14, 'slytherin', 'dog', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 14, 'unicorn hair');
insert into hp_students (age, house, pet, wand_id) values (12, 'hufflepuff', 'ferret', (select count(id) from wands));
 insert into wands (wood, length, core) values ('holly', 12, 'unicorn hair');
insert into hp_students (age, house, pet, wand_id) values (16, 'ravenclaw', 'owl', (select count(id) from wands));
 insert into wands (wood, length, core) values ('yew', 11, 'kneazle whisper');
insert into hp_students (age, house, pet, wand_id) values (11, 'hufflepuff', 'dog', (select count(id) from wands));

